### ISSUE TITLE
can't find these two files

### ISSUE THREAD

**Issue by zjrzjr666** [chenhaoxing/ASL#2]
@chenhaoxing It is a pleasure to read your paper《Shaping Visual Representations with Attributes for Few-Shot Learning (IEEE SPL)》.but I reported an error for missing documents.I can't find these two files. Could you help me check them？thank you！
![image](https://user-images.githubusercontent.com/96851653/187870313-ce8d55aa-6925-452a-b3b0-2568ccb2388a.png)
filename = 'train_data.hdf5'
filename_labels = 'train_labels.json'

**Comment by chenhaoxing** [comment]
> @chenhaoxing It is a pleasure to read your paper《Shaping Visual Representations with Attributes for Few-Shot Learning (IEEE SPL)》.but I reported an error for missing documents.I can't find these two files. Could you help me check them？thank you！ ![image](https://user-images.githubusercontent.com/96851653/187870313-ce8d55aa-6925-452a-b3b0-2568ccb2388a.png) filename = 'train_data.hdf5' filename_labels = 'train_labels.json'


Hello, you can not download the CUB dataset, it automatically downloads the hdf5 format.
Run with "--download".
