### ISSUE TITLE
Nothing was found about a file

### ISSUE THREAD

**Issue by zjrzjr666** [chenhaoxing/ASL#4]
![image](https://user-images.githubusercontent.com/96851653/224608324-4860287f-22b9-4190-87c6-c3efe2f13203.png)

Glad to see your work, but I had a problem running the sun dataset. The file doesn't seem to be in the sun dataset. I didn't find it in the sun data on the download path

**Comment by chenhaoxing** [comment]
Hello, we have uploaded the class_split file in https://github.com/chenhaoxing/ASL/tree/main/datasets/sun.

**Comment by zjrzjr666** [comment]
Thank you very much for your answer, I found that not every image in the SUN dataset has attributes, right? Are images of no attributes in your model also entered?Because I also read this dataset and found that the image will have one more than the image property






朱家瑞
***@***.***







                       
Original Email
                       
                     

Sender:"chx_nju"< ***@***.*** &gt;;

Sent Time:2023/3/14 14:54

To:"chenhaoxing/ASL"< ***@***.*** &gt;;

Cc recipient:"zjrzjr666"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [chenhaoxing/ASL] Nothing was found about a file (Issue #4)




 
Hello, we have uploaded the class_split file in https://github.com/chenhaoxing/ASL/tree/main/datasets/sun.

**Comment by zjrzjr666** [comment]
Oh, I looked carefully at your code and you didn't use it anymore I have no problem, thanks for the answer




朱家瑞
***@***.***







                       
Original Email
                       
                     

Sender:"朱家瑞"< ***@***.*** &gt;;

Sent Time:2023/3/14 18:47

To:"chenhaoxing/ASL"< ***@***.*** &gt;;

Subject:Re:Re: [chenhaoxing/ASL] Nothing was found about a file (Issue #4)


Thank you very much for your answer, I found that not every image in the SUN dataset has attributes, right? Are images of no attributes in your model also entered?Because I also read this dataset and found that the image will have one more than the image property






朱家瑞
***@***.***







                       
Original Email
                       
                     

Sender:"chx_nju"< ***@***.*** &gt;;

Sent Time:2023/3/14 14:54

To:"chenhaoxing/ASL"< ***@***.*** &gt;;

Cc recipient:"zjrzjr666"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [chenhaoxing/ASL] Nothing was found about a file (Issue #4)




 
Hello, we have uploaded the class_split file in https://github.com/chenhaoxing/ASL/tree/main/datasets/sun.
